---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: demo
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: semver:~4.0
    fluxcd.io/locked: "true"
    fluxcd.io/locked_msg: "Halt updates for now"
    fluxcd.io/locked_user: "Stefan Prodan <stefan@weave.works>"
spec:
  releaseName: redis
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: redis
    version: 5.1.3
  valueFileSecrets:
    # the redis-auth secret contains the password value
    - name: redis-auth
  values:
    usePassword: true
    image:
      repository: bitnami/redis
      tag: 4.0.13
    service:
      type: ClusterIP
      port: 6379
    cluster:
      enabled: false
    master:
      securityContext:
        enabled: false
        fsGroup: 0
        runAsUser: 0
      persistence:
        enabled: false
